name: .NET

on:
  push:
    branches: 
     - '*'
  pull_request:
    branches: 
     - '*'

jobs:
  build:

    runs-on: windows-latest

    env:
      ARTIFACT_PATH: ./DbfProtocolsParser/DbfProtocolsParser/bin/Debug/net8.0/win-x86/publish/DbfProtocolsParser.exe

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Debug -a x86 -p:PublishSingleFile=true --self-contained=true

    - name:  Sign Artifact
      run: |
        $cert = Get-PfxCertificate -FilePath ./DbfProtocolsParser/CodeSigningRootCA.pfx -Password (ConvertTo-SecureString -String "password" -AsPlainText -Force)
        Set-AuthenticodeSignature -FilePath ${{ env.ARTIFACT_PATH }} -Certificate $cert

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DbfProtocolsParser.exe
        path: ${{ env.ARTIFACT_PATH }}
